<?php
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>CV</title>';
echo '<style>';
echo '* {';
echo 'max-width: 700px;';
echo 'margin: auto;';
echo '}';
echo '.stuff {';
echo 'display: inline-block;';
echo 'margin-top: 6px;';
echo 'margin-left: 55px;';
echo 'width: 75%;';
echo '';
echo '}';
echo '';
echo '.head {';
echo 'font-size: 20px;';
echo '}';
echo '';
echo '</style>';
echo '</head>';
echo '';
echo '<body>';
echo '';
echo '';
echo '';
echo '<div class="stuff">';
echo '<br><br>';
echo '<h1>CV</h1>';
echo '<h2>Mohammed Alahmadi</h2>';
echo '<hr />';
echo '<br>';
echo '<p class="head">Interests</p>';
echo '<ul>';
echo '';
echo '<li>Photography</li>';
echo '<li>Design</li>';
echo '<li>Programming</li>';
echo '<li>IT</li>';
echo '</ul>';
echo '<p class="head">Skills</p>';
echo '<ul>';
echo '<li>Web Design with HTML & CSS</li>';
echo '</ul>';
echo '<p class="head">Education</p>';
echo '<ul>';
echo '<li>Al-Abna High School</li>';
echo '';
echo '</ul>';
echo '';
echo '';
echo '</div>';
echo '';
echo '';
echo '';
echo '</div>';
echo '</body>';
echo '';
echo '</html>';
?>