<?php
echo '<html>';
echo '';
echo '<head>';
echo '<title>First Lab</title>';
echo '<style>';
echo 'img {';
echo 'border-radius: 100%;';
echo 'position: absolute;';
echo 'right: 50px;';
echo '}';
echo 'table,';
echo 'table td {';
echo 'border: 1px solid #cccccc;';
echo '}';
echo '';
echo 'td {';
echo 'height: 80px;';
echo 'width: 160px;';
echo 'text-align: center;';
echo '}';
echo '#textArea {';
echo 'background-color: black;';
echo 'font: bold;';
echo 'color: white;';
echo 'font-weight: bold;';
echo '';
echo '';
echo '}';
echo '</style>';
echo '</head>';
echo '';
echo '<body style="background-color:green;">';
echo '<h1>CV</h1>';
echo '';
echo '<img src="profile.png" alt="profile img" width="100px" height="100px">';
echo '<br>';
echo '<a href="https://computing.kau.edu.sa/Default-611-AR">FCIT</a>';
echo '<br>';
echo '<a href="cv.php">CV</a>';
echo '<pre>';
echo 'This is MY first';
echo 'semester';
echo 'for';
echo 'CPI405';
echo '&copy;Copy Right for';
echo 'CPIT405';
echo '</pre>';
echo '';
echo '<h2>My current Courses: </h2>';
echo '<ul>';
echo '<li>CPIT405</li>';
echo '<li>CPIT435</li>';
echo '<li>CPIT345</li>';
echo '</ul>';
echo '<h2>My future plans: </h2>';
echo '';
echo '<table border=1>';
echo '<tr>';
echo '<td colspan="2">Work Plan</td>';
echo '</tr>';
echo '<tr >';
echo '<td>Training</td>';
echo '<td>Search job</td>';
echo '</tr>';
echo '<tr>';
echo '<td colspan="2"> travel plan</td>';
echo '</tr>';
echo '<tr>';
echo '<td>visit</td>';
echo '<td>get experience</td>';
echo '</tr>';
echo '<tr>';
echo '<td colspan="2">Thanks</td>';
echo '</tr>';
echo '</table>';
echo '';
echo '<h2>Please fill the following survey:</h2>';
echo '';
echo '<form >';
echo '<label for="fname">First name:</label><br>';
echo '<input type="text" id="fname" name="fname" value=""><br><br>';
echo '<label for="lname">Comments:</label><br>';
echo '<textarea name="comments" rows="10" cols="36"></textarea>';
echo '<br>';
echo '<p>contact: <a href="mailto: abc@example.com">Email</a></p>';
echo '';
echo '<p>Chose one:</p>';
echo '<p>';
echo '<input type="radio"><label>Good</label>';
echo '<input type="radio"><label>Very Good</label>';
echo '<input type="radio"><label>Excellent</label>';
echo '<input type="radio"><label>Satisfied</label>';
echo '<br><br>';
echo 'Rating Survey: <select id="cars" name="cars">';
echo '<option >1</option>';
echo '<option >2</option>';
echo '<option >3</option>';
echo '<option >4</option>';
echo '<option >5</option>';
echo '</select>';
echo '</p>';
echo '</form>';
echo '';
echo '<h1>Warning</h1>';
echo '';
echo '<textarea id="textArea" name="comments" rows="15" cols="50"></textarea>';
echo '';
echo '</body>';
echo '';
echo '</html>';
?>